Milestone : To Do App : Add & Remove
ahmed025566/To-Do-App pull request #2
Opened 2023-02-28 22:29 UTC by ahmed025566

In this mile stone you can see that I have made the following: 

- I have created a function to add a new task to the array of tasks.
- A function to edit the task.
- A function remove the task.
- A function to add a special style when you click in the task to add it.
- Another function when you click outside the task to make every thing normal again.

2023-02-28 22:50 UTC, Gambit142 requested changes
Hi @ahmed025566 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Function for editing tasks exists ✔️ 
- Function for adding tasks exists ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-02-28 22:50 UTC, Gambit142 commented on src/functions.js
> +    };
- [ ] Kindly set the `index` to be equal to the length of the current array. This means that the `first` task should have an `index` of `1` and the `second` task should be equal to `2`. Therefore the code should be `index: tasks.length + 1` 👍 😎

2023-02-28 22:50 UTC, Gambit142 commented on src/functions.js
> +  }
- [ ] When I try to delete a task, it doesn't delete. Only the last one deletes after pressing the delete button twice. It would be nice to fix this. 👍 😎

2023-03-01 14:38 UTC, julie-ify requested changes
Hi @ahmed025566,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 14:38 UTC, julie-ify commented on src/functions.js
> +};
- [ ] When I delete a task it deletes everything in the local storage although the remaining tasks are left on the page, so that when I refresh the page all tasks are gone on the page as well. Kindly fix that.

2023-03-01 17:48 UTC, merged